name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo apt-get install python3-venv 
        make setup
    - name: Run tests
      run: make tests
