name: CI

on: [push]

jobs:
  build:

    runs-on: python:3.7.3

    steps:
    - uses: actions/checkout@v1
    - name: build entire pipeline
      run: make all
    - name: Run tests
      run: make tests